### ISSUE TITLE
explain the name

### ISSUE THREAD

**Issue by rockymeza** [fusionbox/django-ogmios#5]

**Comment by rockymeza** [comment]
:+1:

**Comment by acatton** [comment]
[Gallic god of eloquence](https://en.wikipedia.org/wiki/Ogmios)? I don't understand the issue.

**Comment by cbg** [comment]
Pretty sure he means you should explain it in the README

**Comment by rockymeza** [comment]
since when do emails have anything to do eloquence? or french gods? I'm not
sure I'm seeing the connection here

-rocky
